image: ubuntu:xenial

before_script:
  - apt-get update
  - apt-get -y install sudo curl git file
  - curl -sf https://raw.githubusercontent.com/brson/multirust/master/blastoff.sh | sh -s -- --yes
  - multirust default nightly

stages:
  - test
  - deploy

job1:
  stage: test
  script:
    - cargo test -v --manifest-path glsl-to-spirv/Cargo.toml
    - cargo test -v --manifest-path vulkano-shaders/Cargo.toml
    - cargo build -v --manifest-path vulkano/Cargo.toml

pages:
  stage: deploy
  only:
    - master
  script:
    - cargo doc --manifest-path vulkano/Cargo.toml
    - rm -rf public
    - mkdir public
    - cp target/doc/* public
  artifacts:
    paths:
    - public
