[package]
name = "examples"
version = "0.1.0"
authors = ["Pierre Krieger <pierre.krieger1708@gmail.com>"]
publish = false

[dependencies]
vulkano = { path = "../vulkano" }
vulkano-shader-derive = { path = "../vulkano-shader-derive" }
vulkano-win = { path = "../vulkano-win" }
cgmath = "0.14.1"
image = "0.14.0"
winit = "0.7.0"
time = "0.1.37"
